# Generated by Django 5.2.1 on 2025-06-12 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='credits',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.CharField(default='Computer Science', max_length=100),
        ),
    ]
